/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author das6287
 */
import Model.DBInteract;

public class GUIDesign1 extends javax.swing.JFrame {
    
    /**
     * Creates new form GUIDesign1
     */
    public GUIDesign1() {
        initComponents();
        new DBInteract();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fatalityRadio = new javax.swing.JRadioButton();
        growthRadio = new javax.swing.JRadioButton();
        countryCombo = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputText = new javax.swing.JTextArea();
        dateCombo = new javax.swing.JComboBox<>();
        dateLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COVID-19");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fatalityRadio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fatalityRadio.setText("Fatality Rate");
        fatalityRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatalityRadioActionPerformed(evt);
            }
        });

        growthRadio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        growthRadio.setText("Growth Rate");
        growthRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                growthRadioActionPerformed(evt);
            }
        });

        countryCombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        countryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "",
            "Afghanistan" ,
            "Albania" ,
            "Algeria",
            "Andorra" ,
            "Angola" ,
            "Antigua and Barbuda",
            "Argentina" ,
            "Armenia" ,
            "Australia",
            "Austria" ,
            "Azerbaijan",
            "Bahamas" ,
            "Bahrain" ,
            "Bangladesh",
            "Barbados" ,
            "Belarus" ,
            "Belgium" ,
            "Belize" ,
            "Benin" ,
            "Bhutan" ,
            "Bolivia" ,
            "Bosnia and Herzegovina" ,
            "Botswana" ,
            "Brazil" ,
            "Brunei" ,
            "Bulgaria" ,
            "Burkina Faso" ,
            "Burma" ,
            "Burundi" ,
            "Cabo Verde" ,
            "Cambodia" ,
            "Cameroon" ,
            "Canada" ,
            "Central African Republic" ,
            "Chad" ,
            "Chile" ,
            "China" ,
            "Colombia" ,
            "Congo (Brazzaville)" ,
            "Congo (Kinshasa)" ,
            "Costa Rica" ,
            "Cote d'Ivoire",
            "Croatia",
            "Cuba" ,
            "Cyprus" ,
            "Czechia" ,
            "Denmark" ,
            "Diamond Princess" ,
            "Djibouti" ,
            "Dominica" ,
            "Dominican Republic" ,
            "Ecuador" ,
            "Egypt" ,    "El Salvador" ,
            "Equatorial Guinea" ,
            "Eritrea" ,
            "Estonia" ,
            "Eswatini" ,    "Ethiopia" ,
            "Fiji" ,
            "Finland" ,
            "France" ,
            "Gabon" ,
            "Gambia" ,
            "Georgia" ,
            "Germany" ,
            "Ghana" ,
            "Greece" ,
            "Grenada" ,
            "Guatemala" ,
            "Guinea" ,
            "Guinea-Bissau" ,
            "Guyana" ,    "Haiti" ,
            "Holy See" ,
            "Honduras" ,
            "Hungary" ,    "Iceland" ,
            "India" ,
            "Indonesia" ,
            "Iran" ,    "Iraq" ,    "Ireland" ,    "Israel" ,
            "Italy" ,
            "Jamaica" ,
            "Japan" ,
            "Jordan" ,
            "Kazakhstan" ,
            "Kenya" ,
            "Korea, South" ,
            "Kosovo" ,
            "Kuwait" ,
            "Kyrgyzstan" ,
            "Laos" ,    "Latvia" ,
            "Lebanon" ,
            "Liberia" ,
            "Libya" +
            "Liechtenstein" ,
            "Lithuania" ,
            "Luxembourg" ,
            "Madagascar" ,
            "Malawi" ,
            "Malaysia" ,
            "Maldives" ,
            "Mali" ,    "Malta" ,
            "Mauritania" ,
            "Mauritius" ,
            "Mexico" ,
            "Moldova" ,    "Monaco" ,    "Mongolia" ,
            "Montenegro" ,
            "Morocco" ,
            "Mozambique" ,
            "MS Zaandam" ,
            "Namibia" ,
            "Nepal" ,
            "Netherlands" ,
            "New Zealand" ,
            "Nicaragua" ,
            "Niger" ,
            "Nigeria" ,
            "North Macedonia" ,
            "Norway" ,    "Oman" ,
            "Pakistan" ,
            "Panama" ,    "Papua New Guinea" ,
            "Paraguay" ,
            "Peru" ,    "Philippines" ,    "Poland" ,
            "Portugal" ,
            "Qatar" ,
            "Romania" ,
            "Russia" ,
            "Rwanda" ,
            "Saint Kitts and Nevis" ,
            "Saint Lucia" ,
            "Saint Vincent and the Grenadines" ,
            "San Marino" ,
            "Sao Tome and Principe" ,
            "Saudi Arabia" ,
            "Senegal" ,
            "Serbia" ,
            "Seychelles" ,
            "Sierra Leone" ,
            "Singapore" ,
            "Slovenia" ,
            "Somalia" ,    "South Africa" ,
            "South Sudan" ,
            "Spain" ,
            "Sri Lanka" ,
            "Sudan" ,    "Suriname" ,
            "Sweden" ,
            "Switzerland" ,
            "Syria" ,
            "Taiwan*" ,    "Tanzania" ,
            "Thailand" ,
            "Timor-Leste" ,
            "Togo" ,
            "Trinidad and Tobago" ,
            "Tunisia" ,
            "Turkey" ,
            "Uganda" ,
            "Ukraine" ,
            "United Arab Emirates" ,
            "United Kingdom" ,
            "Uruguay" ,
            "US" ,
            "Uzbekistan" ,
            "Venezuela" ,
            "Vietnam" ,
            "West Bank and Gaza" ,
            "Western Sahara" ,
            "Yemen" ,
            "Zambia",
            "Zimbabwe"}));

submitButton.setBackground(new java.awt.Color(0, 153, 51));
submitButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
submitButton.setText("Submit");
submitButton.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        submitButtonActionPerformed(evt);
    }
    });

    outputText.setColumns(20);
    outputText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    outputText.setRows(5);
    jScrollPane1.setViewportView(outputText);

    dateCombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    dateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1/22/2020", "1/23/2020", "1/24/2020", "1/25/2020", "1/26/2020", "1/27/2020", "1/28/2020", "1/29/2020", "1/30/2020", "1/31/2020", "2/1/2020", "2/2/2020", "2/3/2020", "2/4/2020", "2/5/2020", "2/6/2020", "2/7/2020", "2/8/2020", "2/9/2020", "2/10/2020", "2/11/2020", "2/12/2020", "2/13/2020", "2/14/2020", "2/15/2020", "2/16/2020", "2/17/2020", "2/18/2020", "2/19/2020", "2/20/2020", "2/21/2020", "2/22/2020", "2/23/2020", "2/24/2020"
        , "2/25/2020", "2/26/2020", "2/27/2020", "2/28/2020", "2/29/2020", "3/1/2020", "3/2/2020"
        , "3/3/2020", "3/4/2020", "3/5/2020", "3/6/2020", "3/7/2020", "3/8/2020", "3/9/2020", "3/10/2020", "3/11/2020", "3/12/2020", "3/13/2020", "3/14/2020", "3/15/2020", "3/16/2020", "3/17/2020", "3/18/2020", "3/19/2020", "3/20/2020", "3/21/2020", "3/22/2020", "3/23/2020", "3/24/2020", "3/25/2020", "3/26/2020", "3/27/2020", "3/28/2020", "3/29/2020", "3/30/2020", "3/31/2020"
        , "4/1/2020", "4/2/2020", "4/3/2020", "4/4/2020", "4/5/2020", "4/6/2020", "4/7/2020", "4/8/2020", "4/9/2020", "4/10/2020", "4/11/2020", "4/12/2020", "4/13/2020", "4/14/2020", "4/15/2020", "4/16/2020", "4/17/2020", "4/18/2020", "4/19/2020", "4/20/2020" }));

dateLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
dateLabel.setText("Date");

countryLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
countryLabel.setText("Country");

clearButton.setBackground(new java.awt.Color(204, 51, 0));
clearButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
clearButton.setText("Clear");
clearButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    clearButtonActionPerformed(evt);
    }
    });

    headingLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
    headingLabel.setForeground(new java.awt.Color(178, 34, 34));
    headingLabel.setText("COVID-19");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addComponent(fatalityRadio)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(growthRadio)
                    .addGap(18, 18, 18)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(146, Short.MAX_VALUE))))
        .addGroup(layout.createSequentialGroup()
            .addGap(169, 169, 169)
            .addComponent(dateLabel)
            .addGap(127, 127, 127)
            .addComponent(countryLabel)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(207, 207, 207))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headingLabel)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dateLabel)
                .addComponent(countryLabel))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(growthRadio)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fatalityRadio)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(67, 67, 67)))
            .addGap(35, 35, 35)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fatalityRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatalityRadioActionPerformed
        //makes the other radio button unselect
        growthRadio.setSelected(false);
    }//GEN-LAST:event_fatalityRadioActionPerformed

    private void growthRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_growthRadioActionPerformed
        fatalityRadio.setSelected(false);
    }//GEN-LAST:event_growthRadioActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //converts the objects in to strings and assings them to an variable
        String dateSelected = dateCombo.getSelectedItem().toString();
        String countrySelected = countryCombo.getSelectedItem().toString();
        
        if (growthRadio.isSelected() == true){
            if ("".equals(countrySelected) || "".equals(dateSelected)){
              outputText.setText("One or more choices is not selected. Try again");
            }
            else{
                //sends the selected information to DBInteract class
                String output = DBInteract.getCountryGrowthRate(dateSelected, countrySelected);
                String output2 = DBInteract.getWorldGrowthRate(dateSelected);
                //sets the text to the values calculated in DBInteract
                outputText.setText(countrySelected + "'s COVID-19 growth rate from previous day is: "+ output + "%" 
                        + "\n\n\nThe World COVID-19 growth rate from previous day is: " + output2 + "%");
            }
        }    
        else if (fatalityRadio.isSelected() == true){
            if ("".equals(countrySelected) || "".equals(dateSelected)){
              outputText.setText("One or more choices is not selected. Try again");
            }
            else{
                //sends the selected information to DBInteract class
                String output = DBInteract.getCountryDeathRate(dateSelected, countrySelected);
                String output2 = DBInteract.getWorldDeathRate(dateSelected);
                //sets the text to the values calculated in DBInteract
                outputText.setText(countrySelected + "'s COVID-19 increase in deaths from previous day is: "+ output + "%" 
                        + "\n\n\nThe World COVID-19 increase in deaths from previous day is: " + output2 + "%");
            }      
        }
        else{
            outputText.setText("A rate is not selected.");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        growthRadio.setSelected(false);
        fatalityRadio.setSelected(false);
        outputText.setText("");
        countryCombo.setSelectedItem("");
        dateCombo.setSelectedItem("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDesign1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDesign1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDesign1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDesign1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIDesign1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> countryCombo;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JComboBox<String> dateCombo;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton fatalityRadio;
    private javax.swing.JRadioButton growthRadio;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputText;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
